version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pm_internship
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pm_internship
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
