apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pm-backend
  template:
    metadata:
      labels:
        app: pm-backend
    spec:
      containers:
        - name: backend
          image: pm-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pm-backend
spec:
  selector:
    app: pm-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
